[features]
seeds = false
[programs.localnet]
hello_world = "2MVfj8ghRjjioXeW7rBAUHvWjTDQuw8WJqZAvQaJJAED"

[programs.devnet]
hello_world = "2MVfj8ghRjjioXeW7rBAUHvWjTDQuw8WJqZAvQaJJAED"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/alsjourney/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
