[features]
seeds = false
skip-lint = false
[programs.devnet]
hello_world = "3PawvNMSTx2QrUhRGqr7aqDTuDhM2AZVqq9gn3zm6oXT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/alsjourney/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
